#!/usr/bin/env bash
BINDIR="$(cd $(dirname $0)/../bin && pwd)"
SRCDIR="$(cd $(dirname $0)/../src && pwd)"
rm -r "$HOME/.local/bin"
ln -sv "$BINDIR" "$HOME/.local/bin"
echo "collatz.c"
gcc -Wall "$SRCDIR/collatz.c" -o "$BINDIR/collatz"
echo "piano.c"
gcc -Wall "$SRCDIR/piano.c" -lm -o "$BINDIR/piano"
echo "typewrite.c"
gcc -Wall "$SRCDIR/typewrite.c" -lm -o "$BINDIR/typewrite"
sudo cp -v "$BINDIR/piano" "/usr/local/bin/setuid-piano"
sudo chmod -v +s "/usr/local/bin/setuid-piano"
sudo cp -v "$BINDIR/typewrite" "/usr/local/bin/setuid-typewrite"
sudo chmod -v +s "/usr/local/bin/setuid-typewrite"
