#!/usr/bin/env bash
CONFIGDIR="$(dirname "${BASH_SOURCE[0]}")/../config"
[[ -e "$HOME/.nanorc" ]] && rm -v "$HOME/.nanorc"
ln -sv "$CONFIGDIR/.nanorc" "$HOME/.nanorc"
[[ -e "$HOME/.xinitrc" ]] && rm -v "$HOME/.xinitrc"
ln -sv "$CONFIGDIR/.xinitrc" "$HOME/.xinitrc"
[[ -e "$HOME/.zlogin" ]] && rm -v "$HOME/.zlogin"
ln -sv "$CONFIGDIR/.zlogin" "$HOME/.zlogin"
[[ -e "$HOME/.zshrc" ]] && rm -v "$HOME/.zshrc"
ln -sv "$CONFIGDIR/.zshrc" "$HOME/.zshrc"
[[ -e "$HOME/.config/compton.conf" ]] && rm -v "$HOME/.config/compton.conf"
ln -sv "$CONFIGDIR/compton.conf" "$HOME/.config/compton.conf"
[[ -e "$HOME/.config/conky/conky.conf" ]] && rm -v "$HOME/.config/conky/conky.conf"
ln -sv "$CONFIGDIR/conky.conf" "$HOME/.config/conky/conky.conf"
[[ -e "$HOME/.config/fontconfig/fonts.conf" ]] && rm -fv "$HOME/.config/fontconfig/fonts.conf"
ln -sv "$CONFIGDIR/fonts.conf" "$HOME/.config/fontconfig/fonts.conf"
[[ -e "$HOME/.atom/styles.less" ]] && rm -fv "$HOME/.atom/styles.less"
ln -sv "$CONFIGDIR/styles.less" "$HOME/.atom/styles.less"
sudo cp -v "$CONFIGDIR/.nanorc" "/root/.nanorc"
sudo cp -v "$CONFIGDIR/lightdm-gtk-greeter.conf" "/etc/lightdm/lightdm-gtk-greeter.conf"
sudo cp -v "$CONFIGDIR/locale.conf" "/etc/locale.conf"
