#!/usr/bin/env bash
CONFDIR="$(cd $(dirname $0)/../conf && pwd)"
ln -fsv "$CONFDIR/.default#ap" "$HOME/.ne/.default#ap"
ln -fsv "$CONFDIR/.keys" "$HOME/.ne/.keys"
ln -fsv "$CONFDIR/.login_ascii" "$HOME/.login_ascii"
ln -fsv "$CONFDIR/.login_neofetch" "$HOME/.login_neofetch"
ln -fsv "$CONFDIR/.nanorc" "$HOME/.nanorc"
ln -fsv "$CONFDIR/.xinitrc" "$HOME/.xinitrc"
ln -fsv "$CONFDIR/.zprofile" "$HOME/.zprofile"
ln -fsv "$CONFDIR/.zshenv" "$HOME/.zshenv"
ln -fsv "$CONFDIR/.zshrc" "$HOME/.zshrc"
ln -fsv "$CONFDIR/compton.conf" "$HOME/.config/compton.conf"
ln -fsv "$CONFDIR/conky.conf" "$HOME/.config/conky/conky.conf"
ln -fsv "$CONFDIR/fonts.conf" "$HOME/.config/fontconfig/fonts.conf"
ln -fsv "$CONFDIR/htoprc" "$HOME/.config/htop/htoprc"
ln -fsv "$CONFDIR/pacaur" "$HOME/.config/pacaur/config"
ln -fsv "$CONFDIR/styles.less" "$HOME/.atom/styles.less"
sudo cp -v "$CONFDIR/.default#ap" "/root/.ne/.default#ap"
sudo cp -v "$CONFDIR/.keys" "/root/.ne/.keys"
sudo cp -v "$CONFDIR/.nanorc" "/root/.nanorc"
sudo cp -v "$CONFDIR/issue" "/etc/issue"
sudo cp -v "$CONFDIR/lightdm-gtk-greeter.conf" "/etc/lightdm/lightdm-gtk-greeter.conf"
sudo cp -v "$CONFDIR/locale.conf" "/etc/locale.conf"
sudo cp -v "$CONFDIR/vconsole.conf" "/etc/vconsole.conf"
