#!/usr/bin/env bash
CONFIGDIR="$(cd $(dirname $0)/../config && pwd)"
rm "$HOME/.nanorc"
ln -sv "$CONFIGDIR/.nanorc" "$HOME/.nanorc"
rm "$HOME/.xinitrc"
ln -sv "$CONFIGDIR/.xinitrc" "$HOME/.xinitrc"
rm "$HOME/.zlogin"
ln -sv "$CONFIGDIR/.zlogin" "$HOME/.zlogin"
rm "$HOME/.zshrc"
ln -sv "$CONFIGDIR/.zshrc" "$HOME/.zshrc"
rm "$HOME/.config/compton.conf"
ln -sv "$CONFIGDIR/compton.conf" "$HOME/.config/compton.conf"
rm "$HOME/.config/conky/conky.conf"
ln -sv "$CONFIGDIR/conky.conf" "$HOME/.config/conky/conky.conf"
rm "$HOME/.config/fontconfig/fonts.conf"
ln -sv "$CONFIGDIR/fonts.conf" "$HOME/.config/fontconfig/fonts.conf"
rm "$HOME/.atom/styles.less"
ln -sv "$CONFIGDIR/styles.less" "$HOME/.atom/styles.less"
sudo cp -v "$CONFIGDIR/.nanorc" "/root/.nanorc"
sudo cp -v "$CONFIGDIR/lightdm-gtk-greeter.conf" "/etc/lightdm/lightdm-gtk-greeter.conf"
sudo cp -v "$CONFIGDIR/locale.conf" "/etc/locale.conf"
